"""

Revision ID: 43109a69dcdc
Revises: 
Create Date: 2024-05-25 16:29:27.537439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43109a69dcdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_emotion',
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('emotion_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], ),
    sa.PrimaryKeyConstraint('photo_id', 'emotion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_emotion')
    op.drop_table('emotions')
    # ### end Alembic commands ###
